### ISSUE TITLE
Code is verbose.

### ISSUE THREAD

**Issue by xSypherr** [xKiraiChan/InstanceHistory#1]
Line 44. `private System.Collections.Generic.List<string> history = new System.Collections.Generic.List<string>();`
Why are you using System.Collections.Generic.List when you already reference the assembly? skid.

**Comment by xKiraiChan** [comment]
I am using `System.Collections;`
I am **not** using `System.Collections.Generic`
`Collections.Generic.List` is not valid.
Either I would have to add a using directive for `System.Collections.Generic`, or I would have to fully qualify `List`

**Comment by xKiraiChan** [comment]
Also, "reference the assembly" is the wrong term. 
References are something entirely different

**Comment by xSypherr** [comment]
I meant using skid fuck you shit code noob stop tring to bi original

**Comment by xKiraiChan** [comment]
Archived: https://web.archive.org/web/20210708063711/https://github.com/xKiraiChan/InstanceHistory/issues/1
